//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artisaneer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> GenderID { get; set; }
        public string ImageSource { get; set; }
        public string LGA { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string StandardID { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> SkillId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
