//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artisaneer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateLGA
    {
        public StateLGA()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int StateLGID { get; set; }
        public Nullable<byte> StateID { get; set; }
        public string LGName { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual State State { get; set; }
    }
}
